apiVersion: v1
kind: Service
metadata:
  name: devops-learning-db
  namespace: devops-learning
  labels:
    service: database
spec:
  type: ExternalName
  externalName: devops-learning-db.cveph9nmftjh.eu-west-1.rds.amazonaws.com
  ports:
  - port: 5432