apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: devops-learning
type: Opaque
data:
  # Encoded values - in production, use a secrets management system like AWS Secrets Manager
  # These are base64 encoded - use `echo -n "your-value" | base64` to generate
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # postgrespassword
  SECRET_KEY: ZGV2LXNlY3JldC1rZXk=  # dev-secret-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-learning
data:
  # Database configuration
  DATABASE_URL: "postgresql://postgres:postgrespassword@devops-learning-db.devops-learning.svc.cluster.local:5432/devops_learning"
  FLASK_DEBUG: "0"